name: Deployment to repsO2 server

on:
  push:
    branches:
      - repsO2*
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  deploy_job:
    name: Deploy to repsO2
    runs-on: ubuntu-latest
    if: ${{ github.push.pusher.name == 'goalman96' || github.  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove temp from remote server
        # path to deletefile to remove files from cache
        run: curl https://eso.vse.cz/~repsO2/bookshop/eshop/www/deleteCacheDir.php
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: "eso.vse.cz"
          username: "repsO2"
          # v repozitáři musí být secret SSH_PRIVATE_KEY, v kterém bude privátní klíč bez hesla, odpovídající veřejný klíč musí být nahraný na eso
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # cd do rootu projektu
          script: |
            cd public_html/bookshop
            rm -rf ./*

      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: "eso.vse.cz"
          username: "repsO2"
          port: 22
          # stejný klíč jako v předchozím kroku
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"
          #cesta k rootu projektu
          target: "/home/repsO2/public_html/bookshop"
      - name: grant access to log and temp
        uses: appleboy/ssh-action@master
        with:
          host: "eso.vse.cz"
          username: "repsO2"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd public_html/bookshop/eshop
            mkdir log
            chmod 777 log
            mkdir temp
            chmod 777 temp
